apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: vmware-corp
  description: The VMware organization
  links:
    - url: https://www.vmware.com
      title: Website
spec:
  type: organization
  profile:
    displayName: VMware 
    email: vmware@vmware.com
    picture: https://blogs.vmware.com/cloudprovider/files/2021/09/logo-vmware-tanzu-square-Header-327x324.png
  children: [it-market]
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: vmware-group
  description: The VMware group
spec:
  targets:
    - ./department.yaml
    - ./team.yaml