apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  name: inclusion
spec:
  acceptedServiceBindings:
  - name: db
    types:
    - postgresql
  build:
    buildpacks: {}
    nonSecretEnv:
    - name: BP_JVM_VERSION
      value: "17"
    path: ../..
  ports:
  - name: main
    port: 8080
  replicas: 2
  resources:
    cpu: "400"
    memory: "678"
