apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: inclusion
  description: This is an application that promotes inclusion 
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  targets:
    - ./groups/org.yaml
    - ./resources/database/resource-postgres.yaml
    - ./components/service/component.yaml
    - ./systems/system.yaml
    - ./domains/domain.yaml
